version: '3.8'

services:
  backend:
    build: .
    container_name: revtec-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src/uploads:/app/src/uploads
      - ./database.sqlite:/app/database.sqlite
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - OCR_SPACE_API_KEY=${OCR_SPACE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - revtec-network

  frontend:
    build: ../frontend-rev
    container_name: revtec-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${FRONTEND_URL}
    networks:
      - revtec-network

networks:
  revtec-network:
    driver: bridge
